#Gradle
org.gradle.jvmargs=-Xmx4096M -Dkotlin.daemon.jvm.options\="-Xmx4096M"
org.gradle.java.installations.auto-download=true
kotlin.native.cacheKind=none

#Kotlin
kotlin.code.style=official

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.mpp.androidSourceSetLayoutVersion=2
android.suppressUnsupportedCompileSdk=34

# iOS
org.jetbrains.compose.experimental.uikit.enabled=true

# Web
org.jetbrains.compose.experimental.jscanvas.enabled=true

# KMP
kotlin.mpp.enableCInteropCommonization=true

# App version
version=1.0.5